development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "development-key" %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] || "test-key" %>
  
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
